create or replace PROCEDURE                                                                WEB_ECCOR(NUMIDEN IN INTEGER,FECHAT DATE,
  OUT_RESULTSET OUT SYS_REFCURSOR) IS

tRET VENTAS.CT_ECCOR := VENTAS.CT_ECCOR();
rRET VENTAS.CR_ECCOR := VENTAS.CR_ECCOR(0,NULL,NULL,NULL,NULL,0,0,0,0,NULL,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NULL,0,0,0,0,NULL);

CURSOR C_CONSULTA (NUMIDEN_ INTEGER, FECHA_ DATE) IS
  SELECT VENTAS.PVENFIMO.NUMIDEN,
    CAST( VENTAS.PVENFIMO.NOMBRE ||' '||VENTAS.PVENFIMO.APPAT||' '|| VENTAS.PVENFIMO.APMAT AS VARCHAR(80)) AS NOMBRE,
    CAST( 'CALLE ' || NVL(VENTAS.PVDIRECC.CALLE1,'')|| ' # ' || NVL(VENTAS.PVDIRECC.NUMEXT,'') ||
      CASE WHEN RTRIM( LTRIM( NVL(VENTAS.PVDIRECC.NUMINT,''))) = '' THEN '' ELSE ' '||
        LOWER( NVL (VENTAS.PVDIRECC.NUMINT,'')) END ||
      CASE WHEN RTRIM(LTRIM( NVL (VENTAS.PVDIRECC.CALLE3,''))) = '' THEN 
      CASE WHEN LTRIM(RTRIM( NVL (VENTAS.PVDIRECC.CALLE2,''))) ='' THEN '' ELSE ' POR '||
      NVL(VENTAS.PVDIRECC.CALLE2,'') END ELSE ' ENTRE '||
      NVL(VENTAS.PVDIRECC.CALLE2,'')||' Y '||
      NVL(VENTAS.PVDIRECC.CALLE3,'') END AS VARCHAR(128)) AS DIR1,
      CAST('COLONIA '|| NVL(VENTAS.PVDIRECC.COLONIA,'') AS VARCHAR(64)) AS DIR2,
      CAST( NVL (VENTAS.PVDIRECC.CODPOST,'')||' '|| NVL(VENTAS.PVDIRECC.CIUDAD,'')||', '|| NVL(VENTAS.PVDIRECC.ESTADO,'')||', '|| NVL(VENTAS.PVDIRECC.PAIS,'') AS VARCHAR(128)) AS DIR3,
      ROUND( VENTAS.CRTARCLI.LIMITE - VENTAS.CRTARCLI.DISPONIBLE,2) AS SALGLOB,
      VENTAS.CRCORMEN.LIMITE AS LIMITE,
      VENTAS.CRCORMEN.IDIMPRE AS IDIMPRE,
      VENTAS.CREMISIONEDOCTA.PREFIJO AS PREFIJO,
      VENTAS.CRCORMEN.FOLEMISION AS FOLEMISION,
      VENTAS.CREMISIONEDOCTA.IDEMIENT  AS IDEMIENT,
      ROUND(VENTAS.CRTARCLI.DISPONIBLE,2) AS DISPONIBLE,
      VENTAS.CRCORMEN.SITUACION AS SITUACION,
      ROUND(VENTAS.CRCORMEN.CAPIVEN + VENTAS.CRCORMEN.CAPIMOR + 
          VENTAS.CRCORMEN.INTENOR + VENTAS.CRCORMEN.INTEMOR + VENTAS.CRCORMEN.IVAINTNOR + 
          VENTAS.CRCORMEN.IVAINTMOR + NVL(VENTAS.CRCORMEN.GASTOCOBRANZA,0) + VENTAS.CRCORMEN.PAGOTARDIO + 
          VENTAS.CRCORMEN.INTMPLN + VENTAS.CRCORMEN.IVAIMPLN + VENTAS.CRCORMEN.IMP_SERVICIOS,2) AS MINCORR,
      ROUND(VENTAS.CRCORMEN.CAPIPLAN,2) AS CAPIPLAN,
      VENTAS.CRCORMEN.MESATR,
      VENTAS.CRCORMEN.PLANATR,
      VENTAS.CRTARCLI.CVETAR,
      VENTAS.CRINTCOR.INTNOR,
      VENTAS.CRINTCOR.INTMOR,
      VENTAS.CRINTCOR.CAT,
      (SELECT NVL(SUM(VENTAS.CRTARMOV.IMPORTE),0) FROM VENTAS.CRTARMOV WHERE VENTAS.CRTARMOV.NUMIDEN = VENTAS.PVENFIMO.NUMIDEN AND VENTAS.CRTARMOV.NUMPLAN < 1 AND
        VENTAS.CRTARMOV.FECARGA>VENTAS.CRCORMEN.FECHACOR AND VENTAS.CRTARMOV.FECOPE < TIMESTAMPADD(4,1,VENTAS.CRCORMEN.FECHACOR)) AS DIFERIDO,
        (SELECT PUNTOSACT - (SELECT NVL(SUM(VENTAS.CSDETPUN.PUNTOS),0) 
        FROM VENTAS.CSDETPUN 
        WHERE VENTAS.CSDETPUN.NUMIDEN=VENTAS.PVENFIMO.NUMIDEN 
        AND VENTAS.CSDETPUN.FECHA >VENTAS.CRCORMEN.FECHACOR) 
      FROM VENTAS.CSPUNACU WHERE VENTAS.CSPUNACU.NUMIDEN = VENTAS.PVENFIMO.NUMIDEN) AS PUNTOS,
      (SELECT NVL(SUM(VENTAS.CSDETPUN.PUNTOS),0) FROM VENTAS.CSDETPUN 
        WHERE MONTH(VENTAS.CSDETPUN.FECHA) = month(FECHA_)
        AND YEAR(VENTAS.CSDETPUN.FECHA) = year(FECHA_)
        AND VENTAS.CSDETPUN.NUMIDEN = NUMIDEN_
        AND TIPOPR = 10) AS PTOSVENCIDOS,
      (SELECT VENTAS.VCSPORPUN.PORCCAN FROM VENTAS.VCSPORPUN WHERE VENTAS.CRCORMEN.FECHACOR BETWEEN VENTAS.VCSPORPUN.FECINI AND VENTAS.VCSPORPUN.FECFIN) AS PORCCAN,
        VENTAS.CRCORMEN.CAPIVEN + (VENTAS.CRCORMEN.CAPITAL - (SELECT NVL(SUM(VENTAS.CRTARMOV.IMPORTE),0) 
        FROM VENTAS.CRTARMOV  
        WHERE (VENTAS.CRTARMOV.NUMIDEN = VENTAS.PVENFIMO.NUMIDEN 
        AND VENTAS.CRTARMOV.FECOPE BETWEEN TIMESTAMPADD(4,1,TIMESTAMPADD(6,-1,VENTAS.CRCORMEN.FECHACOR)) 
        AND TIMESTAMPADD(4,1,VENTAS.CRCORMEN.FECHACOR)
        AND VENTAS.CRTARMOV.NUMPLAN = 0 
        AND VENTAS.CRTARMOV.NUMATENTO <> 0 ) OR (VENTAS.CRTARMOV.NUMIDEN=VENTAS.PVENFIMO.NUMIDEN 
        AND VENTAS.CRTARMOV.FECARGA = VENTAS.CRCORMEN.FECHACOR))) AS DBASE,
      VENTAS.CRCORMEN.CAPIMOR AS DMORAT,
      NVL(VENTAS.CRCORMEN.GASTOCOBRANZA,0) AS GASTOCOBRANZA,
      VENTAS.CRCORMEN.PAGOTARDIO    AS PAGOTARDIO,
      VENTAS.CRCORMEN.IDCORMEN      AS IDCORMEN,
      NVL(VENTAS.CRJOVREL.ESTADO,0) AS EDOJOV,
      NVL(VENTAS.CRTARCLI.MSGESP,0) AS MSGESP,
      CODIGO_TARJETA,
      VENTAS.CRTARCLI.EXCEPTUADO_RF,
      MINIMORF,
      VENTAS.CRTARCLI.IDPLAZA,
      CRTARCLI.LIMITE AS LIMITE_ACTUAL
  FROM VENTAS.PVENFIMO
    LEFT OUTER JOIN VENTAS.CRTARCLI ON VENTAS.CRTARCLI.NUMIDEN=VENTAS.PVENFIMO.NUMIDEN AND VENTAS.CRTARCLI.CVEBASIC=VENTAS.CRTARCLI.CVETAR
    LEFT OUTER JOIN VENTAS.PVDIRECC ON VENTAS.PVDIRECC.NUMDIR=VENTAS.CRTARCLI.NUMDIR
    LEFT OUTER JOIN VENTAS.CRCORMEN ON VENTAS.CRCORMEN.NUMIDEN=VENTAS.PVENFIMO.NUMIDEN AND VENTAS.CRCORMEN.FECHACOR = FECHA_
    LEFT OUTER JOIN VENTAS.CRINTCOR ON VENTAS.CRINTCOR.FECHAINI=VENTAS.CRCORMEN.FECHACOR  AND VENTAS.CRINTCOR.IDTIPOCLIENTE = VENTAS.CRTARCLI.IDTIPOCLIENTE AND VENTAS.CRINTCOR.IDPLAZA = VENTAS.CRTARCLI.IDPLAZA
    LEFT OUTER JOIN VENTAS.CRJOVREL ON VENTAS.CRJOVREL.IDJOVEN=VENTAS.PVENFIMO.NUMIDEN AND VENTAS.CRJOVREL.TCJOVEN=VENTAS.CRTARCLI.CVETAR
    LEFT OUTER JOIN VENTAS.CREMISIONEDOCTA ON VENTAS.CREMISIONEDOCTA.IDEMISION = VENTAS.CRCORMEN.IDEMISION
  WHERE VENTAS.PVENFIMO.NUMIDEN = NUMIDEN_;


R_CONSULTA C_CONSULTA%ROWTYPE;

V_EXCENTO number;

BEGIN

  rRET.NUMIDEN := 0;
  rRET.NOMBRE := NULL;
  rRET.DIR1 := NULL;
  rRET.DIR2 := NULL;
  rRET.DIR3 := NULL;
  rRET.SALGLOB := 0;
  rRET.LIMITE := 0;
  rRET.IDIMPRE := 0;
  rRET.PREFIJO := NULL;
  rRET.FOLEMISION := 0;
  rRET.IDEMIENT := 0;
  rRET.DISPONIBLE := 0;
  rRET.SITUACION := 0;
  rRET.MINCORR := 0;
  rRET.CAPIPLAN := 0;
  rRET.MESATR := 0;
  rRET.PLANATR := 0;
  rRET.CVETAR := 0;
  rRET.INTNOR := 0;
  rRET.INTMOR := 0;
  rRET.CAT := 0;
  rRET.DIFERIDO := 0;
  rRET.PUNTOS := 0;
  rRET.PTOSVENCIDOS := 0;
  rRET.PORCCAN := 0;
  rRET.DBASE := 0;
  rRET.DMORAT := 0;
  rRET.GASTOCOBRANZA := 0;
  rRET.PAGOTARDIO := 0;
  rRET.IDCORMEN := 0;
  rRET.EDOJOV := 0;
  rRET.MSGESP := 0;
  rRET.CODIGO_TARJETA := NULL;
  rRET.EXCEPTUADO_RF := 0;
  rRET.MINIMORF := 0;
  rRET.IDPLAZA := 0;
  rRET.VALIDO := 0;
  rRET.MENSAJE := NULL;
  rRET.LIMITE_ACTUAL := 0;
  OPEN C_CONSULTA (NUMIDEN,FECHAT);
  LOOP 
    FETCH C_CONSULTA INTO R_CONSULTA;
    EXIT WHEN C_CONSULTA%NOTFOUND;
    
      rRET.NUMIDEN := 0;
      rRET.NOMBRE := NULL;
      rRET.DIR1 := NULL;
      rRET.DIR2 := NULL;
      rRET.DIR3 := NULL;
      rRET.SALGLOB := 0;
      rRET.LIMITE := 0;
      rRET.IDIMPRE := 0;
      rRET.PREFIJO := NULL;
      rRET.FOLEMISION := 0;
      rRET.IDEMIENT := 0;
      rRET.DISPONIBLE := 0;
      rRET.SITUACION := 0;
      rRET.MINCORR := 0;
      rRET.CAPIPLAN := 0;
      rRET.MESATR := 0;
      rRET.PLANATR := 0;
      rRET.CVETAR := 0;
      rRET.INTNOR := 0;
      rRET.INTMOR := 0;
      rRET.CAT := 0;
      rRET.DIFERIDO := 0;
      rRET.PUNTOS := 0;
      rRET.PTOSVENCIDOS := 0;
      rRET.PORCCAN := 0;
      rRET.DBASE := 0;
      rRET.DMORAT := 0;
      rRET.GASTOCOBRANZA := 0;
      rRET.PAGOTARDIO := 0;
      rRET.IDCORMEN := 0;
      rRET.EDOJOV := 0;
      rRET.MSGESP := 0;
      rRET.CODIGO_TARJETA := NULL;
      rRET.EXCEPTUADO_RF := 0;
      rRET.MINIMORF := 0;
      rRET.IDPLAZA := 0;
      rRET.LIMITE_ACTUAL := 0;
      IF R_CONSULTA.NUMIDEN = 0 THEN
        rRET.VALIDO := 0;
        rRET.MENSAJE := 'NO SE HAN ENCONTRADO DATOS';
      ELSE  
        rRET.VALIDO := 1;
        rRET.MENSAJE := 'EXITO';
      END IF;
      
      rRET.NUMIDEN := R_CONSULTA.NUMIDEN;
      rRET.NOMBRE := R_CONSULTA.NOMBRE;
      rRET.DIR1 :=  R_CONSULTA.DIR1;
      rRET.DIR2 :=  R_CONSULTA.DIR2;
      rRET.DIR3 :=  R_CONSULTA.DIR3;
      rRET.SALGLOB := R_CONSULTA.SALGLOB;
      rRET.LIMITE := R_CONSULTA.LIMITE;
      rRET.IDIMPRE := R_CONSULTA.IDIMPRE;
      rRET.PREFIJO := R_CONSULTA.PREFIJO;
      rRET.FOLEMISION := R_CONSULTA.FOLEMISION;
      rRET.IDEMIENT :=   R_CONSULTA.IDEMIENT;
      rRET.DISPONIBLE := R_CONSULTA.DISPONIBLE;
      rRET.SITUACION := R_CONSULTA.SITUACION;
      rRET.MINCORR := R_CONSULTA.MINCORR;
      rRET.CAPIPLAN := R_CONSULTA.CAPIPLAN;
      rRET.MESATR := R_CONSULTA.MESATR;
      rRET.PLANATR := R_CONSULTA.PLANATR;
      rRET.CVETAR := R_CONSULTA.CVETAR;
      rRET.INTNOR := R_CONSULTA.INTNOR;
      rRET.INTMOR := R_CONSULTA.INTMOR;
      rRET.CAT := R_CONSULTA.CAT;
      rRET.DIFERIDO := R_CONSULTA.DIFERIDO;
      rRET.PUNTOS := R_CONSULTA.PUNTOS;
      rRET.PTOSVENCIDOS := R_CONSULTA.PTOSVENCIDOS;
      rRET.PORCCAN := R_CONSULTA.PORCCAN;
      rRET.DBASE := R_CONSULTA.DBASE;
      rRET.DMORAT := R_CONSULTA.DMORAT;
      rRET.GASTOCOBRANZA := R_CONSULTA.GASTOCOBRANZA;
      rRET.PAGOTARDIO := R_CONSULTA.PAGOTARDIO;
      rRET.IDCORMEN := R_CONSULTA.IDCORMEN;
      rRET.EDOJOV := R_CONSULTA.EDOJOV;
      rRET.MSGESP := R_CONSULTA.MSGESP;
      rRET.CODIGO_TARJETA := R_CONSULTA.CODIGO_TARJETA;
      rRET.EXCEPTUADO_RF := R_CONSULTA.EXCEPTUADO_RF;
      rRET.MINIMORF := R_CONSULTA.MINIMORF;
      rRET.IDPLAZA := R_CONSULTA.IDPLAZA;
      rRET.LIMITE_ACTUAL := R_CONSULTA.LIMITE_ACTUAL;
      
       V_EXCENTO := VENTAS.ESTADIFERIDO_CC(NUMIDEN, FECHAT);
      
      IF V_EXCENTO = 1 THEN        
         rRET.MINCORR := 0;
      END IF;
    tRET.EXTEND;
      tRET(tRET.LAST) := rRET;
        
  END LOOP;
  
     OPEN OUT_RESULTSET FOR
    SELECT 
    T.NUMIDEN,
    T.NOMBRE,
    T.DIR1,
    T.DIR2,
    T.DIR3,
    T.SALGLOB,
    T.LIMITE,
    T.LIMITE_ACTUAL,
    T.IDIMPRE,
    T.PREFIJO,
    T.FOLEMISION,
    T.IDEMIENT,
    T.DISPONIBLE,
    T.SITUACION,
    T.MINCORR,
    T.CAPIPLAN,
    T.MESATR,
    T.PLANATR,
    T.CVETAR,
    T.INTNOR,
    T.INTMOR,
    T.CAT,
    T.DIFERIDO,
    T.PUNTOS,
    T.PTOSVENCIDOS,
    T.PORCCAN,
    T.DBASE,
    T.DMORAT,
    T.GASTOCOBRANZA,
    T.PAGOTARDIO,
    T.IDCORMEN,
    T.EDOJOV,
    T.MSGESP,
    T.CODIGO_TARJETA,
    T.EXCEPTUADO_RF,
    T.MINIMORF,
    T.IDPLAZA,
    T.VALIDO,
    T.MENSAJE
    FROM TABLE (CAST(tRET AS VENTAS.CT_ECCOR)) T;
  CLOSE C_CONSULTA; 
END;